/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package doctor_online_booking;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author danus
 */
public class UserHome extends javax.swing.JFrame {

    //create object to database class
    Database db = new Database();
    //calling DBconnect method using object and main connenction class
    Connection con = db.DBConnect();
    String id;

    /**
     * Creates new form UserHome
     */
    public UserHome(String ID) {
        initComponents();
        id = ID;
        //jTable3.getColumnModel().getColumn(0).setPreferredWidth(200);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jLabel17 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jPasswordField3 = new javax.swing.JPasswordField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jTextField21 = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jTextField22 = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jTextField23 = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jTextField24 = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jButton11 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.setForeground(new java.awt.Color(116, 105, 182));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(116, 105, 182));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doctor_online_booking/Image/user1.png"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 0, 250, 260));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doctor_online_booking/Image/logout.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, 50, 50));
        jPanel1.add(jTabbedPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, -1, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doctor_online_booking/Image/customer_25px.png"))); // NOI18N
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 30, 30));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doctor_online_booking/Image/purchase_40px.png"))); // NOI18N
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 40, 30));

        jButton2.setBackground(new java.awt.Color(153, 255, 255));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("Booking");
        jButton2.setBorder(new javax.swing.border.MatteBorder(null));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, 130, 50));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doctor_online_booking/Image/addUser.png"))); // NOI18N
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 30, 30));

        jButton3.setBackground(new java.awt.Color(153, 255, 255));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 0));
        jButton3.setText("Doctors");
        jButton3.setBorder(new javax.swing.border.MatteBorder(null));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 130, 50));

        jButton1.setBackground(new java.awt.Color(153, 255, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Profile");
        jButton1.setBorder(new javax.swing.border.MatteBorder(null));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 130, 50));

        jButton4.setBackground(new java.awt.Color(0, 0, 204));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Logout");
        jButton4.setBorder(new javax.swing.border.MatteBorder(null));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 550, 140, 40));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doctor_online_booking/Image/dashbord.png"))); // NOI18N
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 20, 30));

        jButton6.setBackground(new java.awt.Color(153, 255, 255));
        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton6.setForeground(new java.awt.Color(0, 0, 0));
        jButton6.setText("Dashboard");
        jButton6.setBorder(new javax.swing.border.MatteBorder(null));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 130, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 610));

        jTabbedPane3.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane3.setForeground(new java.awt.Color(0, 0, 0));

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Online Appointment Booking");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 510, 60));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("<html> <p>  Appointment scheduling systems allow physicians, hospitals, and clinics to effectively connect and integrate all of the appointment channels. Whether your leads originate from a website, a mobile device, or the front desk, having a dynamic and easy-to-use online system for booking appointments makes it the perfect central calendar.  </p>  <br>  <br>   <p>Patient appointment management has received more attention lately, and one of the key elements affecting the whole patient experience is a well-considered strategy. An online scheduling method reduces stress and saves time. Let's look at some of the essential elements of a potent online appointment scheduling system.  </p> </html>");
        jLabel8.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 630, 350));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Healthcare Industry");
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 390, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doctor_online_booking/Image/bg6.jpg"))); // NOI18N
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 629));

        jTabbedPane3.addTab("tab2", jPanel5);

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setText("User ID");
        jPanel6.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, -1, -1));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 0));
        jLabel22.setText("Name");
        jPanel6.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, -1, -1));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 0, 0));
        jLabel23.setText("Password");
        jPanel6.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, -1, -1));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 0));
        jLabel24.setText("Address");
        jPanel6.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, -1, -1));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 0, 0));
        jLabel25.setText("Mobile");
        jPanel6.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, -1, -1));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 0, 0));
        jLabel26.setText("E-mail");
        jPanel6.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, -1, -1));

        jTextField11.setBackground(new java.awt.Color(255, 255, 255));
        jTextField11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTextField11.setForeground(new java.awt.Color(0, 0, 0));
        jPanel6.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 370, 260, -1));

        jTextField12.setBackground(new java.awt.Color(255, 255, 255));
        jTextField12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTextField12.setForeground(new java.awt.Color(0, 0, 0));
        jPanel6.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, 260, -1));

        jTextField13.setBackground(new java.awt.Color(255, 255, 255));
        jTextField13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTextField13.setForeground(new java.awt.Color(0, 0, 0));
        jPanel6.add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 260, -1));

        jPasswordField3.setBackground(new java.awt.Color(255, 255, 255));
        jPasswordField3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPasswordField3.setForeground(new java.awt.Color(0, 0, 0));
        jPanel6.add(jPasswordField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, 260, -1));

        jTextField14.setBackground(new java.awt.Color(255, 255, 255));
        jTextField14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTextField14.setForeground(new java.awt.Color(0, 0, 0));
        jPanel6.add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 260, -1));

        jTextField15.setBackground(new java.awt.Color(255, 255, 255));
        jTextField15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTextField15.setForeground(new java.awt.Color(0, 0, 0));
        jPanel6.add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 260, -1));

        jButton7.setBackground(new java.awt.Color(153, 255, 255));
        jButton7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton7.setForeground(new java.awt.Color(0, 0, 0));
        jButton7.setText("Update");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 430, 100, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doctor_online_booking/Image/bg6.jpg"))); // NOI18N
        jPanel6.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 620));

        jTabbedPane3.addTab("tab3", jPanel6);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 40, 190, -1));

        jButton5.setBackground(new java.awt.Color(116, 105, 182));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 0, 0));
        jButton5.setText("Search");
        jButton5.setBorder(null);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, 80, 30));

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setBackground(new java.awt.Color(255, 230, 230));
        jTable1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTable1.setForeground(new java.awt.Color(0, 0, 0));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.setSelectionForeground(new java.awt.Color(255, 230, 230));
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 630, 150));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Current Service Doctors");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        jButton8.setBackground(new java.awt.Color(116, 105, 182));
        jButton8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton8.setForeground(new java.awt.Color(0, 0, 0));
        jButton8.setText("Search");
        jButton8.setBorder(null);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, 80, 30));
        jPanel2.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 270, 190, -1));

        jTable3.setAutoCreateRowSorter(true);
        jTable3.setBackground(new java.awt.Color(255, 230, 230));
        jTable3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTable3.setForeground(new java.awt.Color(0, 0, 0));
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(jTable3);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 630, 150));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Doctors Available Date");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doctor_online_booking/Image/bg6.jpg"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -40, -1, -1));

        jTabbedPane3.addTab("tab1", jPanel2);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel34.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(0, 0, 0));
        jLabel34.setText("Booking ID");
        jPanel4.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, -1));

        jTextField21.setBackground(new java.awt.Color(255, 255, 255));
        jTextField21.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTextField21.setForeground(new java.awt.Color(0, 0, 0));
        jPanel4.add(jTextField21, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, 260, -1));

        jLabel35.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(0, 0, 0));
        jLabel35.setText("Patient Name");
        jPanel4.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));

        jTextField22.setBackground(new java.awt.Color(255, 255, 255));
        jTextField22.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTextField22.setForeground(new java.awt.Color(0, 0, 0));
        jPanel4.add(jTextField22, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 260, -1));

        jLabel36.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(0, 0, 0));
        jLabel36.setText("Mobile");
        jPanel4.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, -1));

        jTextField23.setBackground(new java.awt.Color(255, 255, 255));
        jTextField23.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTextField23.setForeground(new java.awt.Color(0, 0, 0));
        jPanel4.add(jTextField23, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 260, -1));

        jLabel37.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(0, 0, 0));
        jLabel37.setText("Doctor Name");
        jPanel4.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, -1, -1));

        jTextField24.setBackground(new java.awt.Color(255, 255, 255));
        jTextField24.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTextField24.setForeground(new java.awt.Color(0, 0, 0));
        jPanel4.add(jTextField24, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, 260, -1));

        jLabel38.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(0, 0, 0));
        jLabel38.setText("Appointment Date");
        jPanel4.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, -1, -1));

        jButton9.setBackground(new java.awt.Color(153, 255, 255));
        jButton9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton9.setForeground(new java.awt.Color(0, 0, 0));
        jButton9.setText("Clear");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 400, 110, 50));

        jButton10.setBackground(new java.awt.Color(153, 255, 255));
        jButton10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton10.setForeground(new java.awt.Color(0, 0, 0));
        jButton10.setText("Subbmit");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 400, 110, 50));

        jDateChooser2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.add(jDateChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 320, 260, 40));

        jButton11.setBackground(new java.awt.Color(153, 255, 255));
        jButton11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton11.setForeground(new java.awt.Color(0, 0, 0));
        jButton11.setText("Cancel Booking");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 480, 210, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doctor_online_booking/Image/bg6.jpg"))); // NOI18N
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 630));

        jTabbedPane3.addTab("tab4", jPanel4);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable4.setAutoCreateRowSorter(true);
        jTable4.setBackground(new java.awt.Color(255, 230, 230));
        jTable4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTable4.setForeground(new java.awt.Color(0, 0, 0));
        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable4.setSelectionForeground(new java.awt.Color(255, 230, 230));
        jScrollPane4.setViewportView(jTable4);

        jPanel3.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 630, 170));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Your Bookings");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        jButton12.setBackground(new java.awt.Color(153, 255, 255));
        jButton12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton12.setForeground(new java.awt.Color(0, 0, 0));
        jButton12.setText("Cancel Booking");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 420, 210, -1));

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Booking ID");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, -1, -1));

        jTextField3.setBackground(new java.awt.Color(255, 255, 255));
        jTextField3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, 260, 30));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doctor_online_booking/Image/bg6.jpg"))); // NOI18N
        jLabel12.setText("Your Bookings");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 920, 620));

        jTabbedPane3.addTab("tab5", jPanel3);

        getContentPane().add(jTabbedPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, -30, 720, 640));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doctor_online_booking/Image/bg6.jpg"))); // NOI18N
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(-5, 0, 880, 590));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //call the pannels inside main frame usinf tabs
        jTabbedPane3.setSelectedIndex(1);
        try {

            PreparedStatement p = con.prepareStatement("Select * from details Where id=?");
            p.setString(1, id);
            ResultSet rs = p.executeQuery();
            if (rs.next()) {
                jTextField15.setText(rs.getString(1));
                jTextField14.setText(rs.getString(2));
                jPasswordField3.setText(rs.getString(3));
                jTextField13.setText(rs.getString(4));
                jTextField12.setText(rs.getString(5));
                jTextField11.setText(rs.getString(6));

            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        jTabbedPane3.setSelectedIndex(2);

        //first table view
        try {
            //if clicked again refresh the table to avoid the duplicate values
            jTable1.setModel(new DefaultTableModel());
            String columnName = "Type";
            String conditionValue = "Doctor";
            String qry = "Select Id,FullName,Specialist from details Where Type='Doctor'";
            PreparedStatement p = con.prepareStatement(qry);
            ResultSet rs = p.executeQuery(qry);
            ResultSetMetaData rsmd = rs.getMetaData();
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

            int cols = rsmd.getColumnCount();
            String[] colName = new String[cols];
            for (int i = 0; i < cols; i++) {
                colName[i] = rsmd.getColumnName(i + 1);
                model.setColumnIdentifiers(colName);

                String id, name, sp;
                while (rs.next()) {
                    id = rs.getString(1);
                    name = rs.getString(2);
                    sp = rs.getString(3);

                    String[] row = {id, name, sp};
                    model.addRow(row);
                }

            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }

        //second table view
        jTabbedPane3.setSelectedIndex(2);

        try {
            //if clicked again refresh the table to avoid the duplicate values
            jTable3.setModel(new DefaultTableModel());
            String columnName = "Type";
            String conditionValue = "Doctor";
            String qry = "Select * from doctor_available";
            PreparedStatement p = con.prepareStatement(qry);
            ResultSet rs = p.executeQuery(qry);
            ResultSetMetaData rsmd = rs.getMetaData();
            DefaultTableModel model = (DefaultTableModel) jTable3.getModel();

            int cols = rsmd.getColumnCount();
            String[] colName = new String[cols];
            for (int i = 0; i < cols; i++) {
                colName[i] = rsmd.getColumnName(i + 1);
                model.setColumnIdentifiers(colName);

                String id, name, st, date, sp;
                while (rs.next()) {
                    id = rs.getString(1);
                    name = rs.getString(2);
                    st = rs.getString(3);
                    date = rs.getString(4);
                    sp = rs.getString(5);

                    String[] row = {id, name, st, date, sp};
                    model.addRow(row);
                }

            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jTabbedPane3.setSelectedIndex(3);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        dispose();
        Login l = new Login();
        l.show();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        jTabbedPane3.setSelectedIndex(0);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        try {
            Email_validation v = new Email_validation();
            if (jTextField15.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Enter a ID");
                jTextField15.requestFocus();
            } else if (jTextField14.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Enter a Name");
                jTextField14.requestFocus();
            } else if (jPasswordField3.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Enter a Password");
                jPasswordField3.requestFocus();
            } else if (jTextField13.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Enter a Address");
                jTextField13.requestFocus();
            } else if (jTextField11.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Enter a email");
                jTextField11.requestFocus();
            }else if (!v.isvalid(jTextField11.getText())) {
                JOptionPane.showMessageDialog(null, "invalid Email");
                jTextField11.setText("");
                jTextField11.requestFocus();
            } else if (jTextField12.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Enter a 10 digit number");
                jTextField12.requestFocus();
            } else {
                //validating mobile number is 10 digit
                String number = jTextField12.getText();
                number = number.replace(" ", ""); //if user use space in the mobile field
                boolean valid = number.matches("[0-9]{9,10}");
                if (valid == false) {
                    JOptionPane.showMessageDialog(null, "Enter a 10 digit number");
                    jTextField12.setText("");
                    jTextField12.requestFocus();
                } else {
                    try {
                        String ID = jTextField15.getText();
                        if (ID.equals(id)) {

                            String Name = jTextField14.getText();
                            String pass = jPasswordField3.getText();
                            String Address = jTextField13.getText();
                            int mobile = Integer.parseInt(jTextField12.getText());
                            String email = jTextField11.getText();

                            String sql = "UPDATE details SET FullName=?,Password=?,Address=?,Mobile=?,Email=?,Specialist=?,Type=? WHERE ID=?;";
                            PreparedStatement p = con.prepareStatement(sql);

                            p.setString(1, Name);
                            p.setString(2, pass);
                            p.setString(3, Address);
                            p.setInt(4, mobile);
                            p.setString(5, email);
                            p.setString(6, "");
                            p.setString(7, "User");
                            p.setString(8, ID);
                            p.executeUpdate();
                            JOptionPane.showMessageDialog(null, "Update Complete");
                        } else {
                            JOptionPane.showMessageDialog(null, "User ID Cannot be Change");
                            jTextField15.setText("");
                            jTextField15.requestFocus();

                        }
                    } catch (Exception ex) {
                        JOptionPane.showMessageDialog(null, ex);
                    }
                }
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        jTable1.setModel(new DefaultTableModel());
        String Name = "";
        try {
            //if clicked again refresh the table to avoid the duplicate values
            String search = jTextField1.getText();
            if (search.equals("")) {
                JOptionPane.showMessageDialog(null, "Enter a valid input Doctor Id,Name or which Specialist you want to Know ");
                jTextField1.setText("");
                jTextField1.requestFocus();
                
                jTable1.setModel(new DefaultTableModel());

                        String qry = "Select Id,FullName,Specialist from details Where Type='Doctor'";
                        PreparedStatement p1 = con.prepareStatement(qry);
                        ResultSet rs1 = p1.executeQuery(qry);
                        ResultSetMetaData rsmd1 = rs1.getMetaData();
                        DefaultTableModel model1 = (DefaultTableModel) jTable1.getModel();

                        int cols1 = rsmd1.getColumnCount();
                        String[] colName1 = new String[cols1];
                        for (int i = 0; i < cols1; i++) {
                            colName1[i] = rsmd1.getColumnName(i + 1);
                            model1.setColumnIdentifiers(colName1);

                            String id, name, sp;
                            while (rs1.next()) {
                                id = rs1.getString(1);
                                name = rs1.getString(2);
                                sp = rs1.getString(3);

                                String[] row1 = {id, name, sp};
                                model1.addRow(row1);
                            }

                        }
            } else {

                PreparedStatement p = con.prepareStatement("Select Id,FullName,Specialist from details Where Type='Doctor' AND id=? OR FullName=? OR Specialist=?");
                p.setString(1, search);
                p.setString(2, search);
                p.setString(3, search);
                ResultSet rs = p.executeQuery();
                ResultSetMetaData rsmd = rs.getMetaData();
                DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

                int cols = rsmd.getColumnCount();
                String[] colName = new String[cols];
                for (int i = 0; i < cols; i++) {
                    colName[i] = rsmd.getColumnName(i + 1);
                    model.setColumnIdentifiers(colName);

                    String id, name, sp;
                    while (rs.next()) {
                        id = rs.getString(1);
                        name = rs.getString(2);
                        sp = rs.getString(3);
                        Name = name;
                        String[] row = {id, name, sp};
                        model.addRow(row);
                    }

                }
                if (Name.equals("")) {
                    JOptionPane.showMessageDialog(null, "NO Result found");
                    try {
                        //if clicked again refresh the table to avoid the duplicate values
                        jTable1.setModel(new DefaultTableModel());

                        String qry = "Select Id,FullName,Specialist from details Where Type='Doctor'";
                        PreparedStatement p1 = con.prepareStatement(qry);
                        ResultSet rs1 = p1.executeQuery(qry);
                        ResultSetMetaData rsmd1 = rs1.getMetaData();
                        DefaultTableModel model1 = (DefaultTableModel) jTable1.getModel();

                        int cols1 = rsmd1.getColumnCount();
                        String[] colName1 = new String[cols1];
                        for (int i = 0; i < cols1; i++) {
                            colName1[i] = rsmd1.getColumnName(i + 1);
                            model1.setColumnIdentifiers(colName1);

                            String id, name, sp;
                            while (rs1.next()) {
                                id = rs1.getString(1);
                                name = rs1.getString(2);
                                sp = rs1.getString(3);

                                String[] row1 = {id, name, sp};
                                model1.addRow(row1);
                            }

                        }

                    } catch (Exception ex) {
                        JOptionPane.showMessageDialog(null, ex);
                    }
                }
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        try {

            String search = jTextField2.getText();
            String Name = "";
            if (search.equals("")) {
                JOptionPane.showMessageDialog(null, "Enter a valid input Doctor Id,Name or which Specialist you want to Know ");
                jTextField1.setText("");
                jTextField1.requestFocus();
            } else {
                //if clicked again refresh the table to avoid the duplicate values
                jTable3.setModel(new DefaultTableModel());
                String columnName = "Type";
                String conditionValue = "Doctor";

                String qry = "Select * from doctor_available Where ID=? OR Doctor_name=? OR Specialist=?";
                PreparedStatement p = con.prepareStatement(qry);
                p.setString(1, search);
                p.setString(2, search);
                p.setString(3, search);

                ResultSet rs = p.executeQuery();
                ResultSetMetaData rsmd = rs.getMetaData();
                DefaultTableModel model = (DefaultTableModel) jTable3.getModel();

                int cols = rsmd.getColumnCount();
                String[] colName = new String[cols];
                for (int i = 0; i < cols; i++) {
                    colName[i] = rsmd.getColumnName(i + 1);
                    model.setColumnIdentifiers(colName);

                    String id, name, st, date, sp;
                    while (rs.next()) {
                        id = rs.getString(1);
                        name = rs.getString(2);
                        st = rs.getString(3);
                        date = rs.getString(4);
                        sp = rs.getString(5);
                        Name = name;

                        String[] row = {id, name, st, date, sp};
                        model.addRow(row);
                    }
                }
                jTextField2.setText("");
                jTextField2.requestFocus();

                if (Name.equals("")) {
                    JOptionPane.showMessageDialog(null, "NO Result found");
                    try {

                        jTable3.setModel(new DefaultTableModel());

                        String qry1 = "Select * from doctor_available";
                        PreparedStatement p1 = con.prepareStatement(qry1);
                        ResultSet rs1 = p1.executeQuery();
                        ResultSetMetaData rsmd1 = rs1.getMetaData();
                        DefaultTableModel model1 = (DefaultTableModel) jTable3.getModel();

                        int cols1 = rsmd1.getColumnCount();
                        String[] colName1 = new String[cols1];
                        for (int i = 0; i < cols1; i++) {
                            colName1[i] = rsmd1.getColumnName(i + 1);
                            model1.setColumnIdentifiers(colName1);

                            String id, name, st, date, sp;
                            while (rs1.next()) {
                                id = rs1.getString(1);
                                name = rs1.getString(2);
                                st = rs1.getString(3);
                                date = rs1.getString(4);
                                sp = rs1.getString(5);
                                Name = name;

                                String[] row1 = {id, name, st, date, sp};
                                model1.addRow(row1);
                            }
                        }
                        jTextField2.setText("");
                        jTextField2.requestFocus();

                    } catch (Exception ex) {
                        JOptionPane.showMessageDialog(null, ex);
                    }
                }
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        jTextField21.setText("");
        jTextField22.setText("");

        jTextField23.setText("");
        jTextField24.setText("");
        jTextField21.requestFocus();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        try {
            if (jTextField21.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Enter a ID");
                jTextField21.requestFocus();
            } else if (jTextField22.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Enter a User Name");
                jTextField22.requestFocus();
            } else if (jTextField23.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Enter a 10 digit mobile number");
                jTextField23.requestFocus();
            } else if (jTextField24.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Enter a Doctor Name");
                jTextField24.requestFocus();
            } else {
                //validating mobile number is 10 digit
                String number = jTextField23.getText();
                number = number.replace(" ", ""); //if user use space in the mobile field
                boolean valid = number.matches("[0-9]{9,10}");
                if (valid == false) {
                    JOptionPane.showMessageDialog(null, "Enter a 10 digit number");
                    jTextField23.setText("");
                    jTextField23.requestFocus();
                } else {
                    try {
                        String bid = jTextField21.getText();
                        PreparedStatement p2 = con.prepareStatement("Select * from appointment_details where id=?");
                        p2.setString(1, bid);
                        ResultSet rs = p2.executeQuery();
                        if (rs.next()) {
                            JOptionPane.showMessageDialog(null, "Booking ID Already Taken");
                            jTextField21.setText("");
                            jTextField21.requestFocus();
                        } else {
                            String Doc = jTextField24.getText();
                            PreparedStatement p3 = con.prepareStatement("Select * from details where Type='Doctor' AND FullName=?");
                            p3.setString(1, Doc);
                            ResultSet rs1 = p3.executeQuery();
                            if (rs1.next()) {

                                String Name = jTextField22.getText();
                                // String Doc = jTextField24.getText();
                                String date = ((JTextField) jDateChooser2.getDateEditor().getUiComponent()).getText();
                                int mobile = Integer.parseInt(jTextField23.getText());

                                //convert date string to date format
                                //Date date1=Date.valueOf(date);
                                PreparedStatement p = con.prepareStatement("insert into appointment_details values(?,?,?,?,?,?,?)");
                                p.setString(1, bid);
                                p.setString(2, Name);
                                p.setInt(3, mobile);
                                p.setString(4, Doc);
                                p.setString(5, date);
                                p.setString(6, "On Process");
                                p.setString(7, id);
                                p.executeUpdate();
                                JOptionPane.showMessageDialog(null, "Booking Complete");

                                jTextField21.setText("");
                                jTextField22.setText("");

                                jTextField23.setText("");
                                jTextField24.setText("");
                                jTextField21.requestFocus();

                            } else {
                                JOptionPane.showMessageDialog(null, "Doctor Not Found");
                                jTextField24.setText("");
                                jTextField24.requestFocus();
                            }
                        }
                    } catch (Exception ex) {
                        JOptionPane.showMessageDialog(null, ex);
                    }
                }
            }
        } catch (Exception ex) {

        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        jTabbedPane3.setSelectedIndex(4);

        try {
            //if clicked again refresh the table to avoid the duplicate values
            jTable4.setModel(new DefaultTableModel());

            String qry = "Select * from appointment_details Where UserID=?";
            PreparedStatement p = con.prepareStatement(qry);
            p.setString(1, id);
            ResultSet rs = p.executeQuery();
            ResultSetMetaData rsmd = rs.getMetaData();
            DefaultTableModel model = (DefaultTableModel) jTable4.getModel();

            int cols = rsmd.getColumnCount();
            String[] colName = new String[cols];
            for (int i = 0; i < cols; i++) {
                colName[i] = rsmd.getColumnName(i + 1);
                model.setColumnIdentifiers(colName);

                String bid, name, cont, doc, date, st, ID;
                while (rs.next()) {
                    bid = rs.getString(1);
                    name = rs.getString(2);
                    cont = rs.getString(3);
                    doc = rs.getString(4);
                    date = rs.getString(5);
                    st = rs.getString(6);
                    ID = rs.getString(7);
                    String[] row = {bid, name, cont, doc, date, st, ID};
                    model.addRow(row);
                }

            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        try {
            String Book = jTextField3.getText();
            if (jTextField3.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Booking ID Cannot be Empty");
                jTextField3.setText("");
                jTextField3.requestFocus();
            } else {
                PreparedStatement p2 = con.prepareStatement("Select * from appointment_details Where ID=? AND UserID=?");
                p2.setString(1, Book);
                p2.setString(2, id);
                ResultSet rs6 = p2.executeQuery();
                if (rs6.next()) {
                    String bid1 = jTextField3.getText();
                    PreparedStatement p1 = con.prepareStatement("Delete From appointment_details Where ID=?");
                    p1.setString(1, bid1);
                    p1.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Cancel Complete");
                    jTextField3.setText("");
                    try {
                        //if clicked again refresh the table to avoid the duplicate values
                        jTable4.setModel(new DefaultTableModel());

                        String qry = "Select * from appointment_details Where UserID=?";
                        PreparedStatement p = con.prepareStatement(qry);
                        p.setString(1, id);
                        ResultSet rs = p.executeQuery();
                        ResultSetMetaData rsmd = rs.getMetaData();
                        DefaultTableModel model = (DefaultTableModel) jTable4.getModel();

                        int cols = rsmd.getColumnCount();
                        String[] colName = new String[cols];
                        for (int i = 0; i < cols; i++) {
                            colName[i] = rsmd.getColumnName(i + 1);
                            model.setColumnIdentifiers(colName);

                            String bid, name, cont, doc, date, st, ID;
                            while (rs.next()) {
                                bid = rs.getString(1);
                                name = rs.getString(2);
                                cont = rs.getString(3);
                                doc = rs.getString(4);
                                date = rs.getString(5);
                                st = rs.getString(6);
                                ID = rs.getString(7);
                                String[] row = {bid, name, cont, doc, date, st, ID};
                                model.addRow(row);
                            }

                        }

                    } catch (Exception ex) {
                        JOptionPane.showMessageDialog(null, ex);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Booking Id not Found");
                    jTextField3.setText("");
                    jTextField3.requestFocus();
                }
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }

    }//GEN-LAST:event_jButton12ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserHome("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPasswordField jPasswordField3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
